apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar-app
  labels:
    app: radar-app
    version: v1
    tier: frontend
  annotations:
    description: "Weather radar PWA with multi-country support"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: radar-app
  template:
    metadata:
      labels:
        app: radar-app
        version: v1
        tier: frontend
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: radar-app
        image: ghcr.io/mrauhala/radar-app:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101  # nginx user
          runAsGroup: 101 # nginx group
          readOnlyRootFilesystem: false  # nginx needs to write to cache dirs
          capabilities:
            drop:
            - ALL
            add:
            - CHOWN
            - SETUID
            - SETGID
        volumeMounts:
        - name: cache-volume
          mountPath: /var/cache/nginx
        - name: run-volume
          mountPath: /var/run
        env:
        - name: NGINX_ENTRYPOINT_QUIET_LOGS
          value: "1"
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: run-volume
        emptyDir: {}
      securityContext:
        fsGroup: 101
---
apiVersion: v1
kind: Service
metadata:
  name: radar-app-service
  labels:
    app: radar-app
    tier: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: radar-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None
