apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar-app
  labels:
    app: radar-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: radar-app
  template:
    metadata:
      labels:
        app: radar-app
    spec:
      containers:
      - name: radar-app
        image: ghcr.io/mrauhala/radar-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            add:
            - CHOWN
            - SETUID
            - SETGID
            - NET_BIND_SERVICE
---
apiVersion: v1
kind: Service
metadata:
  name: radar-app-service
spec:
  selector:
    app: radar-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
